# Generated by Django 2.0.6 on 2019-03-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0002_auto_20190312_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedItems',
            new_name='RelatedItemsModel',
        ),
    ]
