# Generated by Django 2.0.6 on 2019-03-13 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WikiApp', '0003_auto_20190312_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='postForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
