# Generated by Django 2.0.6 on 2019-03-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WikiApp', '0004_postmodel_postforeignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateditemsmodel',
            name='relatedItemForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
