# Generated by Django 2.0.6 on 2019-03-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0008_auto_20190315_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikiusermodel',
            old_name='userForeignKey',
            new_name='foreignKeyToUser',
        ),
    ]
