# Generated by Django 2.0.6 on 2019-03-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0011_auto_20190315_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiusermodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
