# Generated by Django 2.0.6 on 2019-03-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0013_auto_20190317_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postSubject', models.CharField(max_length=250)),
                ('postText', models.TextField(default='', max_length=2000)),
                ('wiki_post_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='relatedPostSubject',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='relatedpostText',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='relatedwiki_post_image',
        ),
        migrations.AddField(
            model_name='relateditemsmodel',
            name='relatedItemForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WikiApp.PostModel'),
        ),
    ]
