# Generated by Django 2.0.6 on 2019-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0015_auto_20190317_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relateditemsmodel',
            name='relatedpostSubject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='relateditemsmodel',
            name='relatedpostText',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
