# Generated by Django 2.0.6 on 2019-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0017_auto_20190318_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='relateditemsmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relateditemsmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
